### ISSUE TITLE
https://passport.szlcsc.com/ 无法访问吗

### ISSUE THREAD

**Issue by QGB** [seishinkouki/next_oshwhub_autosignin#3]
```
python oshw.py
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4ea1ef6220>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qgb/.local/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='passport.szlcsc.com', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connection.
HTTPSConnection object at 0x7f4ea1ef6220>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "oshw.py", line 13, in <module>
    my_user.login("oshwhub")
  File "/home/qgb/github/next_oshwhub_autosignin/login.py", line 20, in decorate
    return func(*args, **kw)
  File "/home/qgb/github/next_oshwhub_autosignin/login.py", line 63, in login
    r = self.session.get(passport_url)
  File "/home/qgb/.local/lib/python3.8/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/qgb/.local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/qgb/.local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/qgb/.local/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='passport.szlcsc.com', port=443): Max retries exceeded with url: /login (Caused by NewConnectionError('<urllib3.connecti
on.HTTPSConnection object at 0x7f4ea1ef6220>: Failed to establish a new connection: [Errno 110] Connection timed out'))

In [16]:

In [16]: !curl -vvv https://passport.szlcsc.com/
*   Trying 203.107.45.167...
* TCP_NODELAY set
*

 ```

**Comment by seishinkouki** [comment]
https://github.com/seishinkouki/next_oshwhub_autosignin/issues/1
